import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

import '../core/constants.dart';
import 'prompt_service.dart';

/// Service for handling Gemini API calls
///
/// The API key travels in the `x-goog-api-key` header, never in the URL. It
/// used to be a `?key=` query parameter, and `http`'s `ClientException`
/// prints the full request URI — so any network error (DNS, reset, TLS)
/// wrote the key to the terminal and to CI logs. Every message this service
/// raises is also passed through [redact], in case some layer below still
/// echoes it.
class ApiService {
  final String _apiKey;
  final http.Client? _client;

  /// [client] is for tests; by default each call uses `http.post`.
  ApiService(this._apiKey, {this._client});

  /// Header Gemini reads the API key from.
  static const String apiKeyHeader = 'x-goog-api-key';

  /// [text] with the API key — and any `key=` query value — replaced by a
  /// placeholder, so an error message can be printed safely.
  String redact(String text) {
    var out = text;
    if (_apiKey.isNotEmpty) out = out.replaceAll(_apiKey, '<redacted>');
    return out.replaceAllMapped(
      RegExp(r'([?&]key=)[^&\s#]+'),
      (m) => '${m[1]}<redacted>',
    );
  }

  /// Call Gemini API for single file review
  Future<String> reviewSingleFile({
    required String code,
    required String filePath,
    List<String> focusAreas = const [],
    String language = 'en',
  }) async {
    final prompt = await PromptService.buildReviewPrompt(
      code: code,
      filePath: filePath,
      focusAreas: focusAreas,
      language: language,
    );

    return _makeApiCall(prompt);
  }

  /// Call Gemini API for batch review
  Future<String> reviewBatch({
    required Map<String, String> filesContent,
    List<String> focusAreas = const [],
    String language = 'en',
  }) async {
    final prompt = await PromptService.buildBatchReviewPrompt(
      filesContent: filesContent,
      focusAreas: focusAreas,
      language: language,
    );

    return _makeApiCall(prompt, maxTokens: 8192);
  }

  /// Make API call to Gemini with retry logic
  Future<String> _makeApiCall(String prompt, {int? maxTokens}) async {
    final requestBody = {
      'contents': [
        {
          'parts': [
            {'text': prompt},
          ],
        },
      ],
      'generationConfig': {
        'temperature': CodeReviewConstants.temperature,
        'topK': CodeReviewConstants.topK,
        'topP': CodeReviewConstants.topP,
        'maxOutputTokens': maxTokens ?? CodeReviewConstants.maxOutputTokens,
      },
    };

    final uri = Uri.parse(CodeReviewConstants.geminiApiUrl);
    final headers = {
      HttpHeaders.contentTypeHeader: ContentType.json.value,
      apiKeyHeader: _apiKey,
    };
    final body = jsonEncode(requestBody);
    try {
      final client = _client;
      final response =
          await (client == null
                  ? http.post(uri, headers: headers, body: body)
                  : client.post(uri, headers: headers, body: body))
              .timeout(CodeReviewConstants.defaultTimeout);

      if (response.statusCode == 200) {
        try {
          final data = jsonDecode(response.body);
          final candidates = data['candidates'] as List?;

          if (candidates == null || candidates.isEmpty) {
            // This handles cases where the prompt was blocked, etc.
            final feedback = data['promptFeedback'];
            if (feedback != null) {
              final blockReason = feedback['blockReason'];
              final safetyRatings = feedback['safetyRatings'];
              throw ApiException(
                'API returned no candidates. Reason: ${blockReason ?? 'Unknown'}.',
                statusCode: response.statusCode,
                responseBody: 'Safety Ratings: $safetyRatings',
              );
            }
            return 'No response generated by API.';
          }

          final content = candidates[0]['content'];
          if (content == null) {
            return 'No content in API response candidate.';
          }

          final parts = content['parts'] as List?;
          if (parts == null || parts.isEmpty) {
            return 'No parts in API response content.';
          }

          final text = parts[0]['text'] as String?;
          if (text == null) {
            return 'No text in API response part.';
          }

          return text;
        } catch (e) {
          // This catches JSON parsing errors or unexpected structure.
          throw ApiException(
            'Failed to parse successful API response: $e',
            statusCode: response.statusCode,
            responseBody: response.body,
          );
        }
      } else if (response.statusCode == 429 || response.statusCode == 503) {
        // Rate limit or service unavailable - extract retry delay
        final retryAfter = _extractRetryDelay(response);
        throw ApiRateLimitException(
          'Rate limit exceeded',
          retryAfter: retryAfter,
        );
      } else {
        throw ApiException(
          'API request failed',
          statusCode: response.statusCode,
          responseBody: response.body,
        );
      }
    } on ApiRateLimitException {
      rethrow;
    } on ApiTimeoutException {
      rethrow;
    } on ApiException catch (e) {
      // A response body can echo the request; scrub it like the rest.
      throw ApiException(
        redact(e.message),
        statusCode: e.statusCode,
        responseBody: e.responseBody == null ? null : redact(e.responseBody!),
      );
    } catch (e) {
      // `ClientException.toString()` includes the request URI.
      final detail = redact(e.toString());
      if (e is TimeoutException || detail.contains('TimeoutException')) {
        throw ApiTimeoutException('Request timeout: $detail');
      }
      throw ApiException('Failed to call Gemini API: $detail');
    }
  }

  /// Extract retry delay from response headers or body
  int _extractRetryDelay(http.Response response) {
    // Check Retry-After header
    final retryAfterHeader = response.headers['retry-after'];
    if (retryAfterHeader != null) {
      final seconds = int.tryParse(retryAfterHeader);
      if (seconds != null) return seconds;
    }

    // Check response body for retry information
    try {
      final data = jsonDecode(response.body);
      if (data['error'] != null) {
        final error = data['error'];
        // Some APIs return retry delay in error message
        final message = error['message']?.toString() ?? '';
        final delayMatch = RegExp(
          r'retry after (\d+) seconds',
        ).firstMatch(message);
        if (delayMatch != null) {
          return int.parse(delayMatch.group(1)!);
        }
      }
    } catch (_) {
      // Ignore JSON parsing errors
    }

    // Default retry delay
    return 60; // 60 seconds default
  }

  /// Validate API key format
  static bool isValidApiKeyFormat(String apiKey) {
    // Gemini API keys typically start with 'AIza' and are around 39 characters
    return apiKey.startsWith('AIza') && apiKey.length >= 35;
  }
}

/// Custom exception for API errors
class ApiException implements Exception {
  final String message;
  final int? statusCode;
  final String? responseBody;

  ApiException(this.message, {this.statusCode, this.responseBody});

  @override
  String toString() {
    final statusStr = statusCode != null ? ' (Status: $statusCode)' : '';
    final bodyStr = responseBody != null
        ? '\n--- Response Body ---\n$responseBody'
        : '';
    return 'ApiException: $message$statusStr$bodyStr';
  }
}

/// Exception for rate limit errors
class ApiRateLimitException extends ApiException {
  final int retryAfter; // seconds

  ApiRateLimitException(super.message, {required this.retryAfter})
    : super(statusCode: 429);

  @override
  String toString() =>
      'ApiRateLimitException: $message (Retry after: ${retryAfter}s)';
}

/// Exception for timeout errors
class ApiTimeoutException extends ApiException {
  ApiTimeoutException(super.message);

  @override
  String toString() => 'ApiTimeoutException: $message';
}
