/// Service for handling multi-language support
class LanguageService {
  /// Get localized text based on language and key
  static String getText(
    String language,
    String key, [
    Map<String, String>? params,
  ]) {
    final texts = _getTexts(language);
    String text = texts[key] ?? _getTexts('en')[key] ?? key;

    // Replace parameters if provided
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        text = text.replaceAll('{$paramKey}', paramValue);
      });
    }

    return text;
  }

  /// Get all texts for a language
  static Map<String, String> _getTexts(String language) {
    switch (language) {
      case 'vi':
        return _vietnameseTexts;
      case 'ja':
        return _japaneseTexts;
      case 'ko':
        return _koreanTexts;
      case 'zh':
        return _chineseTexts;
      case 'fr':
        return _frenchTexts;
      case 'de':
        return _germanTexts;
      case 'es':
        return _spanishTexts;
      default:
        return _englishTexts;
    }
  }

  // English texts (default)
  static const Map<String, String> _englishTexts = {
    'report_title': '📋 Code Review Report',
    'generated': 'Generated',
    'project': 'Project',
    'total_files_reviewed': 'Total Files Reviewed',
    'section_summary': '📊 SECTION 1: SUMMARY',
    'section_detailed': '🔍 SECTION 2: DETAILED ANALYSIS',
    'overall_results': '🎯 Overall Results',
    'priority_breakdown': '🚦 Priority Breakdown',
    'most_common_issues': '🔍 Most Common Issues',
    'final_verification': '✅ FINAL VERIFICATION',
    'additional_resources': '📚 Additional Resources',
    'generated_by': 'Generated by Code Review Tool',
    'total_files': 'Total Files',
    'files_with_issues': 'Files with Issues',
    'critical_files': 'Critical Files',
    'total_issues': 'Total Issues',
    'success_rate': 'Success Rate',
    'high_priority': '🔴 High',
    'medium_priority': '🟡 Medium',
    'low_priority': '🟢 Clean',
    'high_priority_desc': 'Critical errors or 4+ issues',
    'medium_priority_desc': '1-3 issues to fix',
    'low_priority_desc': 'No issues found',
    'issues_found': 'Issues Found',
    'suggestions': 'Suggestions',
    'ratings': 'Ratings',
    'path': 'Path',
    'priority': 'Priority',
    'reviewed': 'Reviewed',
    'issues': '🐛 Issues',
    'improvements': '🚀 Suggestions',
    'category': 'Category',
    'score': 'Score',
  };

  // Vietnamese texts
  static const Map<String, String> _vietnameseTexts = {
    'report_title': '📋 Báo Cáo Đánh Giá Code',
    'generated': 'Được tạo',
    'project': 'Dự án',
    'total_files_reviewed': 'Tổng số file đã đánh giá',
    'section_summary': '📊 PHẦN 1: TỔNG QUAN',
    'section_detailed': '🔍 PHẦN 2: PHÂN TÍCH CHI TIẾT',
    'overall_results': '🎯 Kết Quả Tổng Quan',
    'priority_breakdown': '🚦 Phân Loại Ưu Tiên',
    'most_common_issues': '🔍 Vấn Đề Phổ Biến Nhất',
    'final_verification': '✅ KIỂM TRA CUỐI CÙNG',
    'additional_resources': '📚 Tài Liệu Tham Khảo',
    'generated_by':
        'Được tạo bởi Code Review Tool (Cao Gia Hiếu - caogiahieu99@gmail.com)',
    'total_files': 'Tổng số file',
    'files_with_issues': 'File có vấn đề',
    'critical_files': 'File nghiêm trọng',
    'total_issues': 'Tổng số vấn đề',
    'success_rate': 'Tỷ lệ thành công',
    'high_priority': '🔴 Cao',
    'medium_priority': '🟡 Trung bình',
    'low_priority': '🟢 Sạch',
    'high_priority_desc': 'Lỗi nghiêm trọng hoặc 4+ vấn đề',
    'medium_priority_desc': '1-3 vấn đề cần sửa',
    'low_priority_desc': 'Không có vấn đề',
    'issues_found': 'Vấn đề tìm thấy',
    'suggestions': 'Đề xuất',
    'ratings': 'Đánh giá',
    'path': 'Đường dẫn',
    'priority': 'Ưu tiên',
    'reviewed': 'Đã đánh giá',
    'issues': '🐛 Vấn đề',
    'improvements': '🚀 Đề xuất',
    'category': 'Danh mục',
    'score': 'Điểm',
  };

  // Japanese texts
  static const Map<String, String> _japaneseTexts = {
    'report_title': '📋 コードレビューレポート',
    'generated': '生成日時',
    'project': 'プロジェクト',
    'total_files_reviewed': 'レビューしたファイル数',
    'section_summary': '📊 セクション1: 概要',
    'section_detailed': '🔍 セクション2: 詳細分析',
    'overall_results': '🎯 全体結果',
    'priority_breakdown': '🚦 優先度別分類',
    'most_common_issues': '🔍 最も一般的な問題',
    'final_verification': '✅ 最終確認',
    'additional_resources': '📚 追加リソース',
    'generated_by': 'Code Review Toolによって生成',
    'total_files': '総ファイル数',
    'files_with_issues': '問題のあるファイル',
    'critical_files': '重要なファイル',
    'total_issues': '総問題数',
    'success_rate': '成功率',
    'high_priority': '🔴 高',
    'medium_priority': '🟡 中',
    'low_priority': '🟢 クリーン',
    'high_priority_desc': '重大なエラーまたは4つ以上の問題',
    'medium_priority_desc': '1-3の修正すべき問題',
    'low_priority_desc': '問題なし',
    'issues_found': '発見された問題',
    'suggestions': '提案',
    'ratings': '評価',
    'path': 'パス',
    'priority': '優先度',
    'reviewed': 'レビュー済み',
    'issues': '🐛 問題',
    'improvements': '🚀 提案',
    'category': 'カテゴリ',
    'score': 'スコア',
  };

  // Korean texts
  static const Map<String, String> _koreanTexts = {
    'report_title': '📋 코드 리뷰 보고서',
    'generated': '생성일',
    'project': '프로젝트',
    'total_files_reviewed': '검토된 총 파일 수',
    'section_summary': '📊 섹션 1: 요약',
    'section_detailed': '🔍 섹션 2: 상세 분석',
    'overall_results': '🎯 전체 결과',
    'priority_breakdown': '🚦 우선순위 분류',
    'most_common_issues': '🔍 가장 일반적인 문제',
    'final_verification': '✅ 최종 확인',
    'additional_resources': '📚 추가 자료',
    'generated_by': 'Code Review Tool에 의해 생성됨',
    'total_files': '총 파일',
    'files_with_issues': '문제가 있는 파일',
    'critical_files': '중요한 파일',
    'total_issues': '총 문제',
    'success_rate': '성공률',
    'high_priority': '🔴 높음',
    'medium_priority': '🟡 보통',
    'low_priority': '🟢 깨끗함',
    'high_priority_desc': '심각한 오류 또는 4개 이상의 문제',
    'medium_priority_desc': '수정할 1-3개의 문제',
    'low_priority_desc': '문제 없음',
    'issues_found': '발견된 문제',
    'suggestions': '제안',
    'ratings': '평가',
    'path': '경로',
    'priority': '우선순위',
    'reviewed': '검토됨',
    'issues': '🐛 문제',
    'improvements': '🚀 제안',
    'category': '카테고리',
    'score': '점수',
  };

  // Chinese texts
  static const Map<String, String> _chineseTexts = {
    'report_title': '📋 代码审查报告',
    'generated': '生成时间',
    'project': '项目',
    'total_files_reviewed': '已审查文件总数',
    'section_summary': '📊 第一部分：摘要',
    'section_detailed': '🔍 第二部分：详细分析',
    'overall_results': '🎯 总体结果',
    'priority_breakdown': '🚦 优先级分类',
    'most_common_issues': '🔍 最常见问题',
    'final_verification': '✅ 最终验证',
    'additional_resources': '📚 附加资源',
    'generated_by': '由代码审查工具生成',
    'total_files': '总文件数',
    'files_with_issues': '有问题的文件',
    'critical_files': '关键文件',
    'total_issues': '总问题数',
    'success_rate': '成功率',
    'high_priority': '🔴 高',
    'medium_priority': '🟡 中',
    'low_priority': '🟢 清洁',
    'high_priority_desc': '严重错误或4个以上问题',
    'medium_priority_desc': '需要修复的1-3个问题',
    'low_priority_desc': '没有发现问题',
    'issues_found': '发现的问题',
    'suggestions': '建议',
    'ratings': '评分',
    'path': '路径',
    'priority': '优先级',
    'reviewed': '已审查',
    'issues': '🐛 问题',
    'improvements': '🚀 建议',
    'category': '类别',
    'score': '分数',
  };

  // French texts
  static const Map<String, String> _frenchTexts = {
    'report_title': '📋 Rapport de Révision de Code',
    'generated': 'Généré',
    'project': 'Projet',
    'total_files_reviewed': 'Total des fichiers révisés',
    'section_summary': '📊 SECTION 1: RÉSUMÉ',
    'section_detailed': '🔍 SECTION 2: ANALYSE DÉTAILLÉE',
    'overall_results': '🎯 Résultats Globaux',
    'priority_breakdown': '🚦 Répartition par Priorité',
    'most_common_issues': '🔍 Problèmes les Plus Courants',
    'final_verification': '✅ VÉRIFICATION FINALE',
    'additional_resources': '📚 Ressources Supplémentaires',
    'generated_by': 'Généré par Code Review Tool',
    'total_files': 'Total des fichiers',
    'files_with_issues': 'Fichiers avec problèmes',
    'critical_files': 'Fichiers critiques',
    'total_issues': 'Total des problèmes',
    'success_rate': 'Taux de réussite',
    'high_priority': '🔴 Élevée',
    'medium_priority': '🟡 Moyenne',
    'low_priority': '🟢 Propre',
    'high_priority_desc': 'Erreurs critiques ou 4+ problèmes',
    'medium_priority_desc': '1-3 problèmes à corriger',
    'low_priority_desc': 'Aucun problème trouvé',
    'issues_found': 'Problèmes trouvés',
    'suggestions': 'Suggestions',
    'ratings': 'Évaluations',
    'path': 'Chemin',
    'priority': 'Priorité',
    'reviewed': 'Révisé',
    'issues': '🐛 Problèmes',
    'improvements': '🚀 Suggestions',
    'category': 'Catégorie',
    'score': 'Score',
  };

  // German texts
  static const Map<String, String> _germanTexts = {
    'report_title': '📋 Code-Review-Bericht',
    'generated': 'Erstellt',
    'project': 'Projekt',
    'total_files_reviewed': 'Gesamtzahl überprüfter Dateien',
    'section_summary': '📊 ABSCHNITT 1: ZUSAMMENFASSUNG',
    'section_detailed': '🔍 ABSCHNITT 2: DETAILLIERTE ANALYSE',
    'overall_results': '🎯 Gesamtergebnisse',
    'priority_breakdown': '🚦 Prioritätsaufschlüsselung',
    'most_common_issues': '🔍 Häufigste Probleme',
    'final_verification': '✅ ABSCHLIESSENDE ÜBERPRÜFUNG',
    'additional_resources': '📚 Zusätzliche Ressourcen',
    'generated_by': 'Erstellt von Code Review Tool',
    'total_files': 'Gesamtdateien',
    'files_with_issues': 'Dateien mit Problemen',
    'critical_files': 'Kritische Dateien',
    'total_issues': 'Gesamtprobleme',
    'success_rate': 'Erfolgsrate',
    'high_priority': '🔴 Hoch',
    'medium_priority': '🟡 Mittel',
    'low_priority': '🟢 Sauber',
    'high_priority_desc': 'Kritische Fehler oder 4+ Probleme',
    'medium_priority_desc': '1-3 zu behebende Probleme',
    'low_priority_desc': 'Keine Probleme gefunden',
    'issues_found': 'Gefundene Probleme',
    'suggestions': 'Vorschläge',
    'ratings': 'Bewertungen',
    'path': 'Pfad',
    'priority': 'Priorität',
    'reviewed': 'Überprüft',
    'issues': '🐛 Probleme',
    'improvements': '🚀 Vorschläge',
    'category': 'Kategorie',
    'score': 'Punktzahl',
  };

  // Spanish texts
  static const Map<String, String> _spanishTexts = {
    'report_title': '📋 Informe de Revisión de Código',
    'generated': 'Generado',
    'project': 'Proyecto',
    'total_files_reviewed': 'Total de archivos revisados',
    'section_summary': '📊 SECCIÓN 1: RESUMEN',
    'section_detailed': '🔍 SECCIÓN 2: ANÁLISIS DETALLADO',
    'overall_results': '🎯 Resultados Generales',
    'priority_breakdown': '🚦 Desglose por Prioridad',
    'most_common_issues': '🔍 Problemas Más Comunes',
    'final_verification': '✅ VERIFICACIÓN FINAL',
    'additional_resources': '📚 Recursos Adicionales',
    'generated_by': 'Generado por Code Review Tool',
    'total_files': 'Total de archivos',
    'files_with_issues': 'Archivos con problemas',
    'critical_files': 'Archivos críticos',
    'total_issues': 'Total de problemas',
    'success_rate': 'Tasa de éxito',
    'high_priority': '🔴 Alta',
    'medium_priority': '🟡 Media',
    'low_priority': '🟢 Limpio',
    'high_priority_desc': 'Errores críticos o 4+ problemas',
    'medium_priority_desc': '1-3 problemas a corregir',
    'low_priority_desc': 'No se encontraron problemas',
    'issues_found': 'Problemas encontrados',
    'suggestions': 'Sugerencias',
    'ratings': 'Calificaciones',
    'path': 'Ruta',
    'priority': 'Prioridad',
    'reviewed': 'Revisado',
    'issues': '🐛 Problemas',
    'improvements': '🚀 Sugerencias',
    'category': 'Categoría',
    'score': 'Puntuación',
  };
}
