import 'catalog.dart';
import 'facts_emit.dart';
import 'manifest_v2.dart';
import 'package_facts.dart';
import 'platform_notes.dart';

/// The app report: what a newcomer reads first, generated from the manifest and
/// the composed packages.
///
/// It lands between `<!-- composer:managed:report -->` markers in
/// `apps/<id>/README.md` (committed, drift-checked by `composer verify`) and on
/// stdout through `composer describe --app <id>`. It answers five questions —
/// identity (b), platforms (c), composition (a), what the shell resolves (d)
/// and what the app may intervene in (e) — from the same [AppView] the
/// generated facts come from, so the page and the code cannot disagree.
///
/// A backticked repo path in the output would be checked by `docs_check` (the
/// report is Markdown), so a path that may not exist — a runner folder of a
/// `scaffold` platform — appears only inside the `flutter create` command
/// block, never as a span.

/// The `.env` file each flavor reads, by the repository's convention.
const Map<String, String> kEnvFiles = {
  'dev': 'env.dev',
  'staging': 'env.stg',
  'prod': 'env.prod',
};

/// The report for [view], Markdown, without the region markers.
String renderReport(AppView view) {
  final decl = view.declaration;
  final derived = derivePlatforms(view);
  final ssl = deriveSslDecisions(view);
  final b = StringBuffer();
  void line([String text = '']) => b.writeln(text);

  line('## ${view.id} — ${decl.name}');
  line(
    'Entry point `${decl.entrypoint}` · generated by '
    '`dart tools/composer/composer.dart sync --app ${view.id}` from '
    '`${view.manifestPath}` · do not edit this block; the same text is '
    'printed by `dart tools/composer/composer.dart describe --app ${view.id}`.',
  );
  line();

  // -- 1. identity ---------------------------------------------------------
  line('### 1. Identity (b)');
  line('| Flavor | Env file | SSL pinning |');
  line('|:--|:--|:--|');
  for (final flavor in decl.flavors.keys) {
    final decision = ssl[flavor];
    final String pinning;
    if (decision == null) {
      pinning = 'n/a — no declared platform can pin TLS';
    } else if (decision.value.isPinned) {
      final n = decision.value.pins!.length;
      pinning = 'pinned ($n pins)';
    } else {
      final why = _cell(decision.value.disabledReason!);
      pinning = decision.source == 'manifest'
          ? 'disabled — $why'
          : 'disabled (default) — $why';
    }
    line('| $flavor | `${kEnvFiles[flavor]}` | $pinning |');
  }
  line();
  if (decl.env.isEmpty) {
    line('No environment keys are declared.');
  } else {
    line('| Env key | Read by | Required in |');
    line('|:--|:--|:--|');
    for (final e in decl.env) {
      final readBy = e.nativeOnly
          ? 'native only (Gradle / Xcode) — no Dart reader'
          : 'Dart (`String.fromEnvironment`)';
      final required = e.requiredIn.isEmpty ? '—' : e.requiredIn.join(', ');
      line('| `${e.key}` | $readBy | $required |');
    }
  }
  line();

  // -- 2. platforms --------------------------------------------------------
  line('### 2. Platforms (c) — effective values, `value (source)`');
  line(
    '| Platform | Runner | Splash | Push | Deep links | Orientation | '
    'TLS pinning | Window |',
  );
  line('|:--|:--|:--|:--|:--|:--|:--|:--|');
  for (final platform in derived) {
    line(
      '| ${platform.name} '
      '| ${platform.runner.value} (${platform.runner.source}) '
      '| ${platform.splash.value} (${_cell(platform.splash.source)}) '
      '| ${platform.push.value ? 'on' : 'off'} '
      '(${_cell(platform.push.source)}) '
      '| ${platform.deepLinks.value ? 'on' : 'off'} '
      '(${platform.deepLinks.source}) '
      '| ${_orientation(platform.orientation.value)} '
      '(${platform.orientation.source}) '
      '| ${_tls(platform.name)} '
      '| ${_window(platform.window)} |',
    );
  }
  line();

  final scaffold = [
    for (final p in derived)
      if (p.runner.value == 'scaffold') p.name,
  ];
  if (scaffold.isNotEmpty) {
    line(
      'The runner of ${scaffold.join(', ')} is not in the repository. Create '
      'it once, from the app directory, then declare it `runner: committed`:',
    );
    line();
    line('```bash');
    line('cd ${view.dir}');
    line(
      'flutter create --platforms=${scaffold.join(',')} --org com.example '
      '--project-name ${view.pubspecName} .',
    );
    line('```');
    line();
    line('Native notes (not checked):');
    for (final name in scaffold) {
      for (final note in kPlatformNotes[name] ?? const <String>[]) {
        line('- **$name** — $note');
      }
    }
    line();
  }

  final declared = {for (final p in derived) p.name};
  line('Not targeted — and what blocks it:');
  for (final name in kPlatformNames) {
    if (declared.contains(name)) continue;
    final blockers = <String>[];
    for (final entry in view.packageFacts.entries) {
      final facts = entry.value;
      if (!facts.supports(name)) blockers.add(entry.key);
    }
    if (blockers.isEmpty) {
      line(
        '- **$name** — no composed package blocks it; declare it under '
        '`platforms:` and add its runner.',
      );
    } else {
      line(
        '- **$name** — ${blockers.join(', ')} '
        '${blockers.length == 1 ? 'does' : 'do'} not support it '
        '(`platforms:` in the package pubspec).',
      );
    }
  }
  line();

  // -- 3. composition ------------------------------------------------------
  line('### 3. Composition, in boot order (a)');
  line('| # | Group (phase) | Packages | Why |');
  line('|:-:|:--|:--|:--|');
  var n = 0;
  for (final group in view.groups) {
    n++;
    line(
      '| $n | ${group.name} (${group.phase}) | ${group.packages.join(', ')} '
      '| ${_cell(group.why ?? '')} |',
    );
  }
  line();
  line(
    'Modules: ${view.modules.map((m) => '${m.id} (${m.layers.join(', ')})').join(' · ')}.',
  );
  line();
  final provides = <String>[];
  for (final name in view.composed.toList()..sort()) {
    final facts = view.packageFacts[name];
    for (final need in facts?.appProvides ?? const <AppProvides>[]) {
      final where = need.perFlavor
          ? 'one registration per flavor (${decl.flavors.keys.join(', ')})'
          : 'one registration';
      final hint = need.hint.replaceAll('<id>', view.id);
      provides.add(
        '- `${need.type}` for `$name`: $where.'
        '${hint.isEmpty ? '' : ' $hint.'}',
      );
    }
  }
  if (provides.isEmpty) {
    line('**This app must provide:** nothing beyond its composition.');
  } else {
    line('**This app must provide:**');
    for (final p in provides) {
      line(p);
    }
    line();
    line(
      'The DI smoke test boots every flavor, so a missing registration fails '
      'it with "<Type> is not registered".',
    );
  }
  line();

  // -- 4. what the shell resolves -----------------------------------------
  line('### 4. What the shell resolves from this app (d)');
  line('| Capability | Contract | Need | State | If absent |');
  line('|:--|:--|:--|:--|:--|');
  for (final row in view.catalog.requiredRows) {
    line(
      '| `${row.id}` | `${row.type}` | **required** | registered by the '
      'shell\'s own packages | ${_cell(row.whenAbsent)} |',
    );
  }
  for (final row in view.catalog.optional) {
    final state = view.capability(row.id);
    final stateText = state == null
        ? 'undeclared'
        : state.provided
        ? 'provided'
        : '**absent** — ${_cell(state.reason ?? '')}';
    line(
      '| `${row.id}` | `${row.type}` | optional | $stateText '
      '| ${_cell(row.whenAbsent)} |',
    );
  }
  line();
  line(
    'The shell\'s catalog is `kShellContracts` in `platform_app_shell`; a '
    'required row is registered by a shell package, an optional one by an app '
    'or a module, and `checkAppContract` holds this table to the graph the app '
    'actually builds. `ISessionStatusStream` has no row: only a module looks '
    'it up.',
  );
  line();

  // -- 5. behaviour values -------------------------------------------------
  line('### 5. Behaviour values (profile)');
  line(
    'Typed Dart in `lib/app/app_profile.dart`, below the generated facts. '
    'A section left out is the template default, and every section type '
    'documents its defaults and ranges: `display:` (`DisplayProfile` — the '
    'design artboard, the scale policy of each window class, the OS '
    'font-size cap, split-screen mode, the phone threshold) and `router:` '
    '(`RouterProfile` — when the entry location is used, the fallback '
    'location). Locale, theme and network limits are still shell defaults '
    '(see the locked list below).',
  );
  line();

  // -- 6. decisions to revisit ----------------------------------------------
  line('### 6. Decisions to revisit before shipping');
  final revisit = <String>[];
  for (final entry in ssl.entries) {
    final decision = entry.value.value;
    if (entry.key != 'dev' && !decision.isPinned) {
      revisit.add(
        '`flavors.${entry.key}.ssl_pinning`: **disabled** — '
        '${_cell(decision.disabledReason!)}',
      );
    }
  }
  for (final id in const ['error_reporter', 'analytics']) {
    final state = view.capability(id);
    if (state != null && !state.provided) {
      revisit.add(
        '`capabilities.$id`: **absent** — ${_cell(state.reason ?? '')}',
      );
    }
  }
  if (revisit.isEmpty) {
    line('None.');
  } else {
    for (final item in revisit) {
      line('- $item');
    }
  }
  line();

  // -- 7. extension points --------------------------------------------------
  line('### 7. Extension points (e)');
  line(
    'Channels: manifest sections (`platforms`, `capabilities`, `flavors`, '
    '`env`, `di_groups`, `modules`) · the profile (`lib/app/app_profile.dart`) '
    '· hooks (`lib/app/app_hooks.dart`, type `const ShellHooks(`: the error '
    'channels, `beforeDependencies`, `afterBoot`, `navigatorObservers`, '
    '`redirect`, `configureWindow`) · contracts the app registers under '
    '`lib/app/`.',
  );
  line();
  line(
    '**Locked** — changing one means editing the shared package, for every '
    'app: supported locales, the palette, request timeouts and headers, '
    'breakpoints, component themes, page transitions, the default '
    'interceptor chain, the 404 page, push channel and icon, deep-link '
    'allow-lists, logger limits, system UI overlay, secure-storage options. '
    'Replacing a shell-owned type by registration order is unsupported: the '
    'first registration of a type wins (GetIt, '
    '`enableRegisteringMultipleInstancesOfOneType`), which works only for '
    'types registered in the `after` groups.',
  );
  return b.toString();
}

/// What the kernel's `OrientationPolicy` constant [policy] does.
String _orientation(String policy) => switch (policy) {
  'phonesPortrait' => 'phone-sized displays portrait, larger free',
  'free' => 'free',
  'portrait' => 'always portrait',
  'landscape' => 'always landscape',
  _ => policy,
};

/// The declared window of a platform, or `—`.
String _window(Sourced<WindowDecl>? window) {
  if (window == null) return '—';
  final decl = window.value;
  final min = decl.min == null
      ? ''
      : ', min ${decl.min!.width} x ${decl.min!.height}';
  return '${decl.initial.width} x ${decl.initial.height}$min '
      '(${window.source}; needs the `configureWindow` hook)';
}

String _tls(String platform) {
  if (kPinnablePlatforms.contains(platform)) {
    return 'can pin (decision per flavor, §1)';
  }
  if (platform == 'web') return 'n/a (the browser owns TLS)';
  return 'n/a (the pinning plugin has no implementation here)';
}

/// [text] safe inside a Markdown table cell.
String _cell(String text) => text.replaceAll('|', r'\|').replaceAll('\n', ' ');

/// `describe --catalog`: the manifest schema (the parse table), the shell's
/// contract catalog and the derived defaults — the three things a manifest
/// author looks up, printed from the same data the tool validates against.
String renderCatalog(ShellCatalog catalog) {
  final b = StringBuffer();
  void line([String text = '']) => b.writeln(text);

  line('MANIFEST KEYS (app_manifest.yaml)');
  line('A key exists only together with the code that reads it.');
  line();
  for (final key in kManifestKeys) {
    line('  ${key.key}');
    line('      type        ${key.type}');
    line('      default     ${key.defaultValue}');
    line('      refused     ${key.validation}');
    line('      read by     ${key.consumer} (${key.reads})');
    line('      replaces    ${key.replaces}');
    line();
  }
  line(
    '  Composition keys (di_groups, modules, extra_dependencies) are '
    'unchanged: see `composer --help`.',
  );
  line();

  line('SHELL CONTRACTS (what `capabilities:` declares)');
  line(
    'A bundle id declares all its members at once; they share one state. '
    'A required row is registered by the shell\'s own packages and needs no '
    'declaration.',
  );
  line();
  line(
    '  ${'id'.padRight(20)} ${'need'.padRight(9)} ${'bundle'.padRight(8)} contract',
  );
  for (final row in catalog.entries) {
    line(
      '  ${row.id.padRight(20)} ${(row.required ? 'required' : 'optional').padRight(9)} '
      '${(row.bundle ?? '').padRight(8)} ${row.type}'
      '${row.many ? ' (many)' : ''}',
    );
  }
  line();
  line('  If absent, the shell:');
  for (final row in catalog.optional) {
    line('    ${row.id.padRight(20)} ${row.whenAbsent}');
  }
  line();

  line('DERIVED DEFAULTS (what the generated facts fill in)');
  line(
    '  TLS pinning can apply on   ${kPinnablePlatforms.join(', ')} '
    '(web: the browser owns TLS; desktop: the pinning plugin has no '
    'implementation)',
  );
  line(
    '  splash                     ios: native; elsewhere dart when '
    'capability splash is provided, else native',
  );
  line(
    '  push                       on when core_notifications is composed '
    'and supports the platform; off on web (no service worker is shipped)',
  );
  line('  deep links                 on');
  line(
    '  orientation                phones_portrait: displays under the phone '
    'threshold locked to portrait',
  );
  line('  window                     none: the shell does not touch it');
  line(
    '  (every platform key above can be set in the manifest; what it sets is '
    'printed with `manifest` as its source)',
  );
  line('  ssl_pinning, dev flavor    disabled — "$kDevPinReason"');
  return b.toString();
}
